language: c
dist: xenial
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - autoconf-archive
    - gcc-multilib

env:
  - HOST="i686-pc-linux-gnu" CFLAGS="-m32" LDFLAGS="-m32"
  - HOST="x86_64-pc-linux-gnu"

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install libssl-dev:i386

script:
  - ./bootstrap
  - ./configure --host=${HOST}
  - make --jobs=$(($(nproc)*3/2)) distcheck
